name: Check Test Before Merging into Develop

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-for-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Access To gradlew
        run: chmod +x ./gradlew

      - name: Retrieve Secrets And Add to Project Directory
        env:
          APPLICATION_SECURITY_YML: ${{ secrets.APPLICATION_SECURITY_YML }}
          FCM_SECRET: ${{ secrets.FCM_SECRET }}
          FCM_SECRET_FILE_NAME: ${{ secrets.FCM_SECRET_FILE_NAME }}
        run: |
          echo $APPLICATION_SECURITY_YML | base64 --decode > src/main/resources/application-security.yml
          echo $FCM_SECRET | base64 --decode > src/main/resources/$FCM_SECRET_FILE_NAME

      - name: Setup Gradle to publish build scans
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: always
          build-scan-publish: true
          build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-service-agree: "yes"

      - name: Build
        run: ./gradlew build --scan